modLoader="javafml"
loaderVersion="${neo_loader_version_range}"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="MeFrp-MC-Mod"
description='''Use ME Frp tunnels for Minecraft LAN and server play.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version_min},${minecraft_version_max})"
ordering="NONE"
side="BOTH"
